name: Coverity Scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  coverity_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Coverity Scan
        uses: coverity/scan-action@master
        with:
          project: "Hasretturhan/library-system"    # GitHub repo ismi
          notification_email: "hasretturhan92@gmail.com"  # Coverity hesabındaki e-posta
          build_command: |
            gcc ./src/*.c -Iinclude -o library.exe
